### ISSUE TITLE
ajout modules et apps

### ISSUE THREAD

**Issue by chrisripp** [batden/ebarista#1]
Bonjour batden
Merci pour ton script, installation impeccable sur Mint 19.02.
J'ai un problème pour compiler eflete s'install t-il sur E23?
Pourrais tu rajouter certains modules et apps dans ton script, comme tu l'avais sur d'anciens script, comme enventor, eflete, rage pythonefl, pinguins, extramenu, weather etc...?
Tout en 1 ce serai super.
Je me satisfait dèja de ce script là ;)
Grand merci.
Une petite chose, a chaque redemarrage, j'ai une erreure de type:
Agent policykit s'est arrêté de façon inattendue.
Une idée

**Comment by batden** [comment]
Salut chrisripp,
Merci pour le retour.
Non, je ne souhaite pas ajouter d'autres applis dans les scripts déjà très longs! C'est beaucoup de boulot à maintenir tout ça, même dans la forme réduite actuelle - et même si j'ai un coup de main de ma compagne Carla. Surtout que je m'occupe également des traductions françaises et qu'il reste encore pas mal de choses à faire dans ce domaine...
Je n'ai testé que Rage et Ephoto comme applis externes aux scripts. Cela compile bien (sans avoir besoin d'autres paquets que ceux déjà pris en compte dans les dépendances). Mais, franchement, d'autres programmes hors environnement existent et ont plus de fonctionnalités... Pour les applis orientés développeurs/designers, je considère qu'à ce niveau, on a pas vraiment besoin d'aide pour l'installation ;)
En outre, beaucoup de programmes disponibles dans les dépôts ne sont plus développés, ou alors de façon intermittente. Nos scripts sont avant tout destinés aux utilisateurs lambda et c'est pour cela que nous nous sommes limités aux fondamentaux, afin d'offrir une expérience agréable qui donne envie d'aller plus loin...
Pour l'erreur Policykit, le support est maintenant assuré en interne par un module dédié : plus besoin de lancer les services Policykit à l'ouverture de session.

**Comment by chrisripp** [comment]
Grand merci pour ton retour.
j'ai réussi a compiler mes appli nikel ;)
