### ISSUE TITLE
errors:

### ISSUE THREAD

**Issue by jlslinux** [batden/ebarista#2]
Hi
I see the following errors:

/home/jls/.local/bin/ebarista.sh: riga 934: errore di sintassi vicino al token non atteso "("
/home/jls/.local/bin/ebarista.sh: riga 934: `        printf "\n%s\n\n" "(do not delete the ccache folder... OK)"'

**Comment by batden** [comment]
Ciao,
Sorry, I cannot reproduce the issue. It may be that you've inadvertently press a key while launching the script...
Please update your local repository and copy the file ebarista.sh from this repo to ~/.local/bin.
Make the script executable then run it again.
